### ISSUE TITLE
Invisible helmet dropping in Zombie Apocalypse Core

### ISSUE THREAD

**Issue by Otateriheem** [Ruu3f/projects#4]
Aren't they meant to never drop ?

![invisible_helmet](https://github.com/user-attachments/assets/fe68db72-1edf-4327-b2a5-b33bab31d013)

**Comment by Ruu3f** [comment]
They were meant to never drop, will fix in the next update. But they're weaker than leather helmets, so it shouldn't be much of a problem.

**Comment by Ruu3f** [comment]
This has been fixed in the latest beta version.

**Comment by Otateriheem** [comment]
Thanks :)

**Comment by avc1657** [comment]
Im still getting the invisible helmet from zombies. Im on version 1.21.1, mod 1.2.1

**Comment by Ruu3f** [comment]
That shouldn't happen, is it happening just on 1.21.1 or on the other versions too?

**Comment by avc1657** [comment]
I only tested in 1.21.1
